# for some issue on some arguments go under documentation
version: '3'
services:
  ### PHP ##############################################
  php:
    build:
      context: ./dev/docker/php
    volumes:
      - ${APP_CODE_PATH_HOST}/:/var/www/html/
    environment:
      - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages
    networks:
      - project
  ### ADMINER ##############################################
  adminer:
    build:
      context: ./dev/docker/adminer
    depends_on:
      - mariadb
    networks:
      - project
    ports:
      - 80
  ### phpMyAdmin ###########################################
  phpmyadmin:
    build:
      context: ./dev/docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
    ports:
      - 80
    depends_on:
      - mariadb
    networks:
      - project
  ### MariaDB ##############################################
  mariadb:
    build:
      context: ./dev/docker/mariadb
    volumes:
      - mariadb:/var/lib/mysql:cached # Persist the database in a Docker volume.
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

    networks:
      - project
  ### Apache Server ########################################
  apache:
    build:
      context: ./dev/docker/apache
    volumes:
      - ${APP_CODE_PATH_HOST}/:/var/www/html/
      - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
      - "${APACHE_HOST_HTTPS_PORT}:443"
    depends_on:
      - php
      - mariadb
    networks:
      - project
  ### RabbitMQ ########################################

  rabbitmq: # The RabbitMQ container.
    build:
      context: ./dev/docker/rabbitmq
    ports:
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq:cached
    networks:
      - project

volumes:
  rabbitmq:
  mariadb:

networks:
  project:

