# for some issue on some arguments go under documentation and read ComposeFileFormat
version: '3'
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PASSWORD}:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
    container_name: ${MYSQL_HOST}
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
      - PMA_USER=${MYADMIN_USER}
      - PMA_PASSWORD= ${MYADMIN_PASSWORD}
    restart: always
    depends_on:
      - mysql
  php:
    build:
      context: './php/'
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php

  apache:
    build:
      context: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "${APACHE_PORT}:80"
    restart: always
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache